<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-16T17:04:04Z" name="Default suite" finished-at="2024-05-16T17:05:20Z" duration-ms="76713">
    <groups>
    </groups>
    <test started-at="2024-05-16T17:04:04Z" name="Default test" finished-at="2024-05-16T17:05:20Z" duration-ms="76713">
      <class name="com.qa.amazon.tests.ProductPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:04:04Z" name="setup" finished-at="2024-05-16T17:04:41Z" duration-ms="37091" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="navigateToProductsPage()[pri:1, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:04:41Z" name="navigateToProductsPage" finished-at="2024-05-16T17:04:52Z" duration-ms="10585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToProductsPage -->
        <test-method signature="checkcountbeforeaddingbroduct()[pri:2, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:04:52Z" name="checkcountbeforeaddingbroduct" finished-at="2024-05-16T17:04:55Z" duration-ms="3080" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.qa.amazon.tests.ProductPageTest.checkcountbeforeaddingbroduct(ProductPageTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkcountbeforeaddingbroduct -->
        <test-method signature="clickonproductTestAndAddToCart()[pri:3, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:04:55Z" name="clickonproductTestAndAddToCart" finished-at="2024-05-16T17:05:16Z" duration-ms="21163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonproductTestAndAddToCart -->
        <test-method signature="checkcountafterddingbroduct()[pri:4, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:05:16Z" name="checkcountafterddingbroduct" finished-at="2024-05-16T17:05:18Z" duration-ms="2442" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.qa.amazon.tests.ProductPageTest.checkcountafterddingbroduct(ProductPageTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkcountafterddingbroduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.amazon.tests.ProductPageTest@33065d67]" started-at="2024-05-16T17:05:18Z" name="tearDown" finished-at="2024-05-16T17:05:20Z" duration-ms="2176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.amazon.tests.ProductPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
